version: "3.9"
services:
  #Nginx
  nginx:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
      - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  #PHP-FPM
  php-fpm:
    container_name: php-fpm
    image: php:fpm
    volumes:
      - ./www:/var/www/html
    networks:
      - app-network
  
  #MySQL
  mysql:
    container_name: mysql
    image: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    env_file:
      - ./services/mysql/.env
    volumes:
      - ./services/mysql/dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network: 
    driver: bridge